### ISSUE TITLE
Define Interactions

### ISSUE THREAD

**Issue by notconfusing** [notconfusing/WIGI#1]
What are the main things the portal will do?
- View Graphs and Charts
  - Two modes:
    - Current
    - Change since last week
  - 13 Graphs from Paper ( \* = focus on, ~ = not now)
    - By Gender (pg16) : do not reduce to just male/female if possible *
    - By Country (pg15)
    - By Date of Death (pg16)
    - By Place of Birth (pg16)
    - By Culture (pg 7, 17-18, female % vs. total biographies: pg14) *
    - By Language of the Biography
    - Overall view of citizen and place of birth (pg11)
    - World population compared (pg12)
    - Gender Range over time (pg19) 
    - Article size/length (pg25) ~
    - Celebrity Terms (pg 26-28) ~
  - 3 Charts from Paper
    - Comparing how WIGI ranks countries vs. other Gender indices (pg13)
    - 
    - 
  - Graphs Not from Paper
    - By-Profession: a breakdown of the jobs the women written about have
- Download Datasets
  - Navigate snapshot points (questions below from Frances)
    - Download current dataset or dataset from last week?
    - Will this include other snapshots or time frames?
    - Will change between snapshot points or time periods be a dataset you can download?

Pages are from the initial paper found here: http://arxiv.org/pdf/1502.03086v1.pdf. However, my notes are certainly not perfect (I don't think the graphs from the paper even add up to 13). Feel free to correct as you see fit.

**Comment by fsoong** [comment]
@notconfusing This is helpful!

Komal and I have to written up our initial understandings in this Google Document: https://docs.google.com/document/d/1eb6HVPMPwE1ZiOCYbcRXh-bv5PR1GGt_i_5_E23_-HQ/edit?usp=sharing

Question: what are snaphots / snapshot points?

**Comment by QEDK** [comment]
Wrt Google Doc, Excel? Why PowerPoint?

**Comment by KomalPatel-github** [comment]
I will create several (rough)layouts by  tomorrow. @notconfusing  could tell which one you liked.

**Comment by fsoong** [comment]
Hi @QEDK, sorry. The visibility on that document was supposed to be hidden to just Komchi, Max, and I.

We will not be using Google Doc, Excel, or PowerPoint to create any of the final outputs (research paper or portal website) for this project. I'm using Google Doc for now as a place to write collaborative notes, because it's convenient.

**Comment by Komchi** [comment]
I am still a bit confused if it should be like a intractable website or not

**Comment by QEDK** [comment]
It has graphs which are interactive. That's what I think, it should be.

**Comment by fsoong** [comment]
I've edited the  original description with my list of what the 13 graphs refer to and questions I still have about what "navigate to snapshot points" means.

**Comment by notconfusing** [comment]
@fsoong . First let's define "snapshot". The data that was used for the original paper was a sampling of Wikidata from October 2014. We plan to re-sample it every week, and look at changes. Each resampling is what I will call a "snapshot" - the WIGI data **as of <insert week>**.  We plan to offer the data used to generate our graphs for each snapshot. Therefore we'll have an interaction that lists the links to each snapshot data. This list will grow longer every week. 

So in regards to" Will change between snapshot points or time periods be a dataset you can download?" We will not for now have a "delta" dataset, it will be up to the dowloader to find the differences each week.

**Comment by notconfusing** [comment]
Here are the most **essential** Graphs in my opinion just to focus on in the meantime:
Legend (*\* = two time variables)
1.  Gender By Culture Latest
   - Gender By Culture By Snaphshot
2. Gender By Country (World Map) Latest
   - Gender By Country (World Map) by Snapshot
3. Gender by Date of Birth 
   - Gender by Date of Birth By Snapshot **
4. Wikipedia Language by Gender (optional by Wikipedia Size) 
   - Wikipedia Language by Gender by Snapshot

**Secondary Priority**
1. Gender by Culture by Date of Birth By Snapshot **
2. Gender by Profession (experimental).
3. Celebrity Percentage by Gender By Decade by Language
   - Celebrity Percentage by Gender By Decade by Language By Snapshot **
4. Wikipedia Language by Mean Article Size by Snapshot.
5. Wikipedia Language by Local Hero Gender
   -  Wikipedia Language by Local Hero Gender by Snapshot
6. Gender by Date of Death 
   - Gender by Date of Death By Snapshot **
