### ISSUE TITLE
Design Visualisation Style

### ISSUE THREAD

**Issue by notconfusing** [notconfusing/WIGI#10]
Designers create a unified visualisation style for how the graphs should look. What labels, ticks, colours should be used for maximum effect.

**Comment by Komchi** [comment]
I will create several (rough)layoust tomorrow. @notconfusing you could tell if you like it or not.

**Comment by fsoong** [comment]
Hi Komal,

As I'm the owner of this task, I'd like if you review them with me first
tomorrow. Please email your rough layouts to fs.soong@gmail.com.

Thanks,
Frances

On Wed, May 6, 2015 at 9:45 AM, Komal Patel notifications@github.com
wrote:

> I will create several (rough)layoust tomorrow. @notconfusing
> https://github.com/notconfusing you could tell if you like it or not.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/notconfusing/WIGI/issues/10#issuecomment-99533889.

## 

Frances Soong
Visual UX Designer
(908) 635-1534
francessoong.com http://www.francessoong.com/
LinkedIn https://www.linkedin.com/in/francessoong | Twitter
https://www.linkedin.com/in/francessoong

**Comment by notconfusing** [comment]
REMINDER: one of the "interactions" we need to design for is socializing the data.

**Comment by raivivek** [comment]
Expecting next set of inputs from Beta release.
