### ISSUE TITLE
Make Portal: Usage Counters

### ISSUE THREAD

**Issue by notconfusing** [notconfusing/WIGI#13]
It's important that the portal be able to count page views and downloads of our datasets. I think if we use apache it can do this.

**Comment by QEDK** [comment]
We can use Google Analytics for page view count.
However, for the download counter, we need MySQL, probably. An easier way to do it would be to make people enter their names, email or something and then count the number of entries. That's easier.

**Comment by Masssly** [comment]
We can find a way to get apache/mysql to both count page views and dataset downloads without asking for names/emails. Most users are just passing by and would not proceed when asked for such details. I won't rule off using Google analytics (for page views only) but its much prettier when we use a single process to achieve both needs.

**Comment by notconfusing** [comment]
Not quite a usage counter, but https://commons.wikimedia.org/wiki/File:Pageviews_and_Downloads_of_WIGI.png

**Comment by notconfusing** [comment]
`cd /var/log/apache2`
`for i in {1..29}; do grep 'csv' access.log.$i | awk '{print $4}' | cut -d: -f1 | uniq -c ; done`
