### ISSUE TITLE
Promote viewing 	

### ISSUE THREAD

**Issue by notconfusing** [notconfusing/WIGI#15]
Write some blogs. Make a video. Do some social media stuff.

**Comment by QEDK** [comment]
Once we're done with Phase A, I'll speak to Signpost and a few WikiProjects which concern us.

**Comment by notconfusing** [comment]
@QEDK brilliant, that'll be a great help.

**Comment by hargup** [comment]
@vivekiitkgp and @notconfusing have written blog posts about the project 
- http://notconfusing.com/wikimania2015/
- http://vivekiitkgp.github.io/programming/wigi-an-inspire-grantee.html

We can do some more promotion but don't need to keep the issue open for that.
