### ISSUE TITLE
Write Longitudinal Statistical Paper

### ISSUE THREAD

**Issue by notconfusing** [notconfusing/WIGI#16]
Write about the trends and their statistical significance. Ideally peer-reviewed. Otherwise Self-published.

**Comment by piokon** [comment]
As usual, count me in on paper writing. Would be happy to chat more 
about that!

Our first paper is still in the first stage review.

## 

Piotr Konieczny, PhD
http://hanyang.academia.edu/PiotrKonieczny
http://scholar.google.com/citations?user=gdV8_AEAAAAJ
http://en.wikipedia.org/wiki/User:Piotrus

**Comment by hargup** [comment]
Count me in too.

**Comment by QEDK** [comment]
I'm in as a researcher. Hargup, aren't you a dev? Devs have a lot of work already. :P

**Comment by hargup** [comment]
I think my inputs in the research can valuable as I have a good enough formal background in Mathematics and Statistics and also because I have an understanding of different aspects of feminism and social justice issue. I understand developers have a lot of work and I with other devs will take care of it irrespective of my contributions to the research team.

**Comment by QEDK** [comment]
Yep, why not?

**Comment by QEDK** [comment]
Btw, you saw the deleted version, I realized that devs "should" help too.

**Comment by notconfusing** [comment]
- [x] since 2013 on the 42 wikis by %
- [x] since 2014 by all variables

**Comment by notconfusing** [comment]
done, see wigi-icwsm.tex

**Comment by piokon** [comment]
Does it mean you wrote a new paper???

## 

Piotr Konieczny, PhD
http://hanyang.academia.edu/PiotrKonieczny
http://scholar.google.com/citations?user=gdV8_AEAAAAJ
http://en.wikipedia.org/wiki/User:Piotrus

**Comment by notconfusing** [comment]
@piokon we wrote a paper that was centered around the technical release of
the dataset. It was rejected by ICWSM, but we are now targeting OpenSym. We
are taking care that it does not overlap with the journal paper in
submission.

Make a great day,
Max Klein ‽ http://notconfusing.com/
