### ISSUE TITLE
Font page content

### ISSUE THREAD

**Issue by raivivek** [notconfusing/WIGI#24]
Hi all,

I have setup a basic site using Nikola having a front page that will introduce out project and break down like top tabbed navigation to different graphs.

What should we put in the first page? A short, compelling description of the project with the info graphic perhaps? I tried finding suitable content from paper but picking up short sections from it wasn't conveying proper picture.

Or perhaps start right away with one of the graphs (doesn't appear attractive to me)

@hargup @notconfusing

**Comment by Masssly** [comment]
@vivekiitkgp Is this going to be the same as the lead capture page? We shouldn't have graphs of any sort there. Will come up with some text for a brief introduction. Then there can be a navigation to the various visualizations neatly placed side by side with the introduction.

**Comment by raivivek** [comment]
@Masssly I think so. yes. A general one line introduction about graphs can also find its place in the text.

**Comment by fsoong** [comment]
Can someone paste the link to it here?

Also, if we've already purchased or have a nice domain name for this project, can we set up the current work in a test subdomain? Like test.wigi.org... and then make wigi.org itself a "coming soon" page where the main call-to-action is a submission field for people to enter their email to hear news about the WIGI project as it's being developed and opportunities to help us out with it (aka be sent surveys / new design / early access). 

My boyfriend would like to write a blog post about how industry researchers can use our dataset(s) to find interesting insights (using his company's program here: https://databricks.com/blog). And I don't have a good place for him to link to (Github and Wiki Meta are not very public-friendly unfortunately.)

**Comment by raivivek** [comment]
Hi fsoong,

I don't think we have a dedicated domain name as such for the project. In
all likelihood, we are hosting wigi website under https://wigi.wmflabs.org
(or similar) address (see #12). I have some static content ready which I
shall try to host on the server today.

Vivek Rai
https://vivekiitkgp.github.io

**Comment by raivivek** [comment]
@fsoong @notconfusing 

Checkout some preliminary stuff here - http://tools-static.wmflabs.org/wigi/output/

I'm still experimenting with web server on tools service.

**Comment by notconfusing** [comment]
@vivekiitkgp for front page text, at the moment you can copy the first [four paragraphs](https://meta.wikimedia.org/wiki/Grants:IdeaLab/WIGI:_Wikipedia_Gender_Index) from our grant. And use the image on there too. We'll update it later.

And you're right we should use wmflabs. However it's 404ing now for me.

**Comment by notconfusing** [comment]
@vivekiitkgp might have been 404'ing because i moved off halva, now i switched to the new server which its running off. Plese move everything over to wigi.eqiad.wmflabs, a more powerful 8-core 16gigram server.

```
Successfully added wigi entry for IP address 208.80.155.156.
Successfully created new proxy wigi.wmflabs.org for backend wigi.wikidumpparse.eqiad.wmflabs:80. 
```

**Comment by notconfusing** [comment]
These are the todos there:
- Front Page
  - Expand width of content to match Header width.
  - An image from Infographic.
  - Text from Grants page.
  - A link to grants page.
  - Later maybe: Splash image.
  - Later maybe: Black and white photograph of one or a few historical women. (High Quality).
  - Big Button with Icon to Download the Data

**Comment by notconfusing** [comment]
- add a single large static image or a carousel of images
