### ISSUE TITLE
deploy WIGI-website on tools-labs

### ISSUE THREAD

**Issue by notconfusing** [notconfusing/WIGI#25]
For @hargup and @vivekiitkgp:

Deploy the nikola/bokeh site on wmflabs.org/wigi/

Search here for FAQ's https://wikitech.wikimedia.org/wiki/Help:Tool_Labs#Web_server

**Comment by notconfusing** [comment]
I am also thinking now, that because of datasharing between wigi.eqiad.wmflabs and tools-labs, we might as well just run the webserver off of wigi.eqiad.wmflabs. And i just set up a proxy for this

`Successfully created new proxy wigi.wmflabs.org for backend wigi.wikidumpparse.eqiad.wmflabs:808`

**Comment by hargup** [comment]
The can now be accessed from https://tools.wmflabs.org/wigi/

**Comment by notconfusing** [comment]
and also at wigi.wmflabs.org
