### ISSUE TITLE
automate aggregation maps

### ISSUE THREAD

**Issue by notconfusing** [notconfusing/WIGI#26]
- pobs_map.json
  - _pob qid_ $\mapsto$ _country qid_
- citizenships_map.csv
  - _citizenship_  $\leftrightarrow$ _english country name_
- country_maps.csv
  - _country qid_ $\leftrightarrow$ _english country name_ $\leftrightarrow$ _world culture_

**Comment by raivivek** [comment]
Seems solved. Closing.
