### ISSUE TITLE
Set up Wikidata Toolkit on WMFLabs

### ISSUE THREAD

**Issue by notconfusing** [notconfusing/WIGI#3]
https://www.mediawiki.org/wiki/Wikidata_Toolkit
1. See if it can be done on tools-labs.
2. If not set it up on an instance
    2. possibly using the wikidumpparse instance I have already created
    2. i-000002ac.eqiad.wmflabs
3. See if the wikidatadump json.bzip file can be accessed instead of downloaded
4. Confirm an example script can run.

**Comment by hargup** [comment]
@notconfusing I've created a new tool name `wigi` at (http://tools.wmflabs.org/) and I've also added you as a manager, I think other people to request access to the tools project before I can add them to the `wigi` tool. Working with `wikitech` is new for me so I would like you to verify if I'm doing things right.

**Comment by notconfusing** [comment]
@hargup, I think it's instructive to set it up locally once the first time.
I found this tutorial to be really helpful.
https://www.mediawiki.org/wiki/Wikidata_Toolkit#Beginner.27s_guide . And
next everything I've learned about Tools-labs I learned from this Help
page: https://wikitech.wikimedia.org/wiki/Help:Tool_Labs

Make a great day,
Max Klein ‽ http://notconfusing.com/

**Comment by notconfusing** [comment]
@hargup . In the mean time you can get the october 2014 snaphshot_data from here: http://notconfusing.com/gender-index-data-2014-09-17.csv (too large to host on github >100mb, but I think now there is a new way to host large data on github, right?)

**Comment by QEDK** [comment]
Yeah, there is. But it's only being rolled out to a few people right now.
If we need it ASAP, you might consider getting in the queue (check the blog
post for the queue link).

From,
QEDK.

~~

**Comment by notconfusing** [comment]
OK @hargup and @vivekiitkgp I've made some progress on this and got wikidata toolkit running.
It's on a dedicated server. So to log in add the following to your `~/.ssh`.

```
Host bastion.wmflabs.org
    User maximilianklein
    Hostname bastion.wmflabs.org
    ProxyCommand none
    IdentityFile ~/.ssh/id_rsa_wikitech

Host *.eqiad.wmflabs
     ProxyCommand ssh -a -W %h:%p bastion.wmflabs.org
     #ProxyCommand mosh -a -W %h:%p bastion.wmflabs.org
     User maximilianklein 
```

except of course changing your usernames and keys etc.

OK then you can log into `ssh halva.eqiad.wmflabs`. Mmm I love halva. 

Once you're in there you can 

```
cd to wdtk-parent/wdtk-examples
mvn compile
mvn exec:java -Dexec.mainClass="org.wikidata.wdtk.examples.DumpProcessingExample" 
```

Please you confirm that you can do everything up to this point!

Now here's the plan going forward:
Except now we just have to put this file in that examples folder: https://github.com/notconfusing/WIGI/blob/master/GenderIndexProcessor.java

And then script running the GenderIndexProcessor every week in schedule with http://dumps.wikimedia.org/other/wikidata/

Then it will save a CSV file that can be read by our python scripts, and we're in the money!

**Comment by notconfusing** [comment]
Update, please read @hargup and @vivekiitkgp 

I was not able to run `GenderIndexProcessor.java` on `halva.eqiad.wmflabs` because of Out of Memory Error. I made a new machine `wigi.eqiad.wmflabs` with 16G of RAM. You should have access to this machine. It runs now, and processes the data dump in 20 mins (takes about 40 mins to dowload the 4g dump).

```
maximilianklein@wigi:~/Wikidata-Toolkit/wdtk-examples$ tail GenderIndexProcessor.out 
*** Found 2813001 items with gender within 17752332 items.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 20:12.814s
[INFO] Finished at: Tue Jun 09 17:38:53 UTC 2015
[INFO] Final Memory: 63M/6407M
[INFO] ------------------------------------------------------------------------
```

To invoke the process, I have setup the crontab to look like

```
0 0 * * 0 /bin/bash /home/maximilianklein/Wikidata-Toolkit/wdtk-examples/run_headless.sh
```

I think that's every Sunday at midnight run the `run_headless.sh` , which itself does this gives it 10gig of memory (takes about 6 gigs right now). And runs it under `nohup`. 

```
export MAVEN_OPTS="-Xmx10000M -Xss512M -XX:MaxPermSize=10000M -XX:+CMSClassUnloadingEnabled"

nohup mvn exec:java -Dexec.mainClass="org.wikidata.wdtk.examples.GenderIndexProcessor" > GenderIndexProcessor.out
```

Last thing is that it saves the .csv files in the `results` folder with the date.

```
maximilianklein@wigi:~/Wikidata-Toolkit/wdtk-examples$ ls results/
gender-index-data-2015-06-09.csv
```

Now we are ready to commence the python processing of the CSV. But we should keep an eye out to make sure the cronjob works.

At the end of next week I will review your work on the front end, and if its servicable I will ask you to switch to writing the python/pandas stage of the stack.
