### ISSUE TITLE
Collect Wikitech usernames

### ISSUE THREAD

**Issue by notconfusing** [notconfusing/WIGI#7]
@hargup @vivekiitkgp once you register at http://wikitech.wikimedia.org/ can you send me your profiles so I can add you to the virtual machines.

**Comment by hargup** [comment]
Mine is `hargup`

**Comment by raivivek** [comment]
It's same as GitHub's - `vivekiitkgp`

**Comment by notconfusing** [comment]
Perfect thanks. Closing now.
